In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('/kaggle/input/crimepredfinal/df1.csv')

In [3]:
df2=pd.read_csv('/kaggle/input/crimepredfinal/df2.csv')

In [4]:
df = pd.concat([df1, df2], ignore_index=True)

In [5]:
df

,District_Name,age,Caste,Profession,Sex,criminal
0,Bagalkot,26.0,VADDA,Labourer,MALE,1
1,Bagalkot,27.0,NaN,NaN,MALE,1
2,Bagalkot,25.0,NaN,NaN,MALE,1
3,Bagalkot,26.0,NaN,NaN,MALE,1
4,Bagalkot,23.0,NaN,NaN,MALE,1
...,...,...,...,...,...,...
4489476,Yadgir,19.0,CHRISTIAN,Student,FEMALE,0
4489477,Yadgir,16.0,"HOLAYA, HOLER, HOLEYA",House help - hired,FEMALE,0
4489478,Yadgir,29.0,Lingayath,Teacher,FEMALE,0
4489479,Yadgir,29.0,REDDY,House help - hired,FEMALE,0
4489480,Yadgir,17.0,KABBALIGA,Student,FEMALE,0

In [6]:
df.loc[:, 'District_Name'].fillna(df['District_Name'].mode()[0], inplace=True)

/tmp/ipykernel_33/1669718941.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:, 'District_Name'].fillna(df['District_Name'].mode()[0], inplace=True)

In [7]:
df.loc[:, 'age'].fillna(df['age'].mode()[0], inplace=True)

/tmp/ipykernel_33/3777720824.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:, 'age'].fillna(df['age'].mode()[0], inplace=True)

In [8]:
most_common_profession = df['Profession'].mode()[0]
df['Profession'].fillna(most_common_profession, inplace=True)

/tmp/ipykernel_33/696078764.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Profession'].fillna(most_common_profession, inplace=True)

In [9]:
most_common_caste= df['Caste'].mode()[0]
df['Caste'].fillna(most_common_profession, inplace=True)

/tmp/ipykernel_33/2156161153.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Caste'].fillna(most_common_profession, inplace=True)

In [10]:
df['Sex'].fillna(df['Sex'].mode()[0], inplace=True)

/tmp/ipykernel_33/2953594873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sex'].fillna(df['Sex'].mode()[0], inplace=True)

In [11]:
missing_values = df.isnull().sum()
print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
District_Name    0
age              0
Caste            0
Profession       0
Sex              0
criminal         0
dtype: int64

In [12]:
df.shape

(4489481, 6)

In [13]:
import pandas as pd
num_rows_to_keep = int(len(df) * 0.1)
df_sampled = df.sample(n=num_rows_to_keep, random_state=42)

In [14]:
df=df_sampled
df

          District_Name   age      Caste  Profession     Sex  criminal
561382   Bengaluru City  29.0     AGNANI      Casual    MALE         1
4398944  Uttara Kannada  48.0       Naik     Farmer     MALE         0
2369165         Raichur  33.0     KURUBA     Farmer     MALE         1
2360736         Raichur  60.0    Farmer      Farmer     MALE         1
2277659     Mysuru Dist  34.0    Farmer      Farmer     MALE         1
...                 ...   ...        ...         ...     ...       ...
4124257     Mysuru Dist  60.0     KURUBA  Housewife   FEMALE         0
1493177          Hassan  35.0  Lingayath     Farmer     MALE         1
1189924     Chitradurga  32.0     NAYAKA     Farmer     MALE         1
4070304  Mangaluru City  25.0    Farmer      Farmer     MALE         0
1897248           Kolar   0.0  BAJANTHRI     Farmer     MALE         1

[448948 rows x 6 columns]

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [16]:
encoder = OneHotEncoder(drop='first')
X_cat = encoder.fit_transform(df[['District_Name', 'Caste', 'Profession', 'Sex']])

In [17]:
scaler = StandardScaler()
X_num = scaler.fit_transform(df[['age']])

In [18]:
X = pd.concat([pd.DataFrame(X_cat.toarray()), pd.DataFrame(X_num, columns=['age'])], axis=1)

In [19]:
X.columns = X.columns.astype(str)

In [20]:
y = df['criminal']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [23]:
y_pred = rf_classifier.predict(X_test)

In [24]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.759060028956454

In [25]:
y_pred

array([1, 0, 1, ..., 1, 0, 0])

In [27]:
def predict_criminal(input_data):
    input_cat = encoder.transform(pd.DataFrame(input_data[['District_Name', 'Caste', 'Profession', 'Sex']]))
    input_num = scaler.transform(pd.DataFrame(input_data['age']))  
    input_features = pd.concat([pd.DataFrame(input_cat.toarray()), pd.DataFrame(input_num, columns=['age'])], axis=1)
    prediction = rf_classifier.predict(input_features)
    return prediction

In [30]:
import joblib
import os
model_filename = '/kaggle/working/crimepredmodel.pkl'
joblib.dump(rf_classifier, model_filename)
print("Model saved to:", model_filename)

Model saved to: /kaggle/working/crimepredmodel.pkl